#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "===> Setting up DB..."
# reset database to a fresh state.

# do other initilization like clearing binaries or emptying kv-storage etc...

echo "==> App is now ready to go!"
